### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
It resulted to error.

### CODE REVIEW

**Comment by neobrain** [comment]
What error? It works just fine for me.

**Comment by ghost** [comment]
As NCCH header was wrong my ctrtool(latest release) results error and
doesn't save files( I tested with 2 games)

**Comment by ghost** [comment]
It doesn't when NCCH header is completely wrong.

**Comment by neobrain** [comment]
Why did you close this? Don't randomly close stuff without explaining why, please.

**Pull request closed without merging**
