### PR TITLE
Update to build with latest upstream ctrulib

### PR DESCRIPTION
**Pull request by CaptainSwag101**
This pull request now features 100% fewer buggy tab-indents!

### CODE REVIEW

**Comment by neobrain** [comment]
Take a look at the diff, you still changed a bunch of spaces for no reason... ;)

**Comment by CaptainSwag101** [comment]
The only spaces I think I changed were ones that didn't quite line up with the indents, but I can fix those if you really want.

**Comment by neobrain** [comment]
Please do - they are intentionally used for horizontal alignment of function arguments.

Also, once you're done please squash your patches into a single commit because the individual patches here don't really contribute to git history otherwise.

**Comment by CaptainSwag101** [comment]
Finished, sorry about all the hassle!

**Comment by neobrain** [comment]
No worries :)

Line 131 has a trailing white space introduced at the end of the line.

**Comment by CaptainSwag101** [comment]
And... fixed.

**Comment by neobrain** [comment]
\o/

Thanks for the contribution :)

**Pull request merged**
